env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - error
    - ignorePackages
  no-plusplus:
    - off
  no-param-reassign:
    - error
    - props: false
  max-len:
    - error
    - code: 80
      ignoreStrings: true
      ignoreTemplateLiterals: true
  operator-linebreak:
    - error
    - after
  comma-dangle:
    - off
