env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false
  babelOptions:
    plugins:
      - '@babel/plugin-syntax-import-assertions'
rules:
  import/extensions:
    - error
    - ignorePackages
