name: Common CI
on:
  pull_request:
  merge_group:

jobs:
  documentation_generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run generate-docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: the132Debuggers/documentation
          publish_branch: main
          publish_dir: ./jsdoc
          commit_message: docs(documentation):${{ github.event.head_commit.message }}

  check_code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: Check Code Style
        run: npm run lint

  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: Check PR Title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm test
