name: Formatting
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Check Format
        run: npm run lint
